name: time_track
description: >-
  A simple command-line time tracking application 
  demonstrating usage of Realm Dart SDK

version: 0.2.0
homepage: https://github.com/realm/realm-dart

environment:
  sdk: ^3.0.2

dependencies: 
  realm_dart: ^3.1.0
  args: ^2.0.0
  dart_console: ^4.1.0

dev_dependencies:
  lints: ^4.0.0
