name: tasktracker
description: MongoDB flexible sync example.
version: 1.0.0

environment:
  sdk: ^3.0.2

dependencies:
  realm_dart: ^3.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
